### ISSUE TITLE
bench-route for clustered environment.

### ISSUE THREAD

**Issue by Pratik32** [zairza-cetb/bench-routes#85]
currently bench-route can monitor routes of an application on a single machine. In many scenarios applications are highly available(HA) & hence run on multiple machines at the same time.
We can enhance bench-route such that it can run on a cluster environment where it can monitor stats of an entire cluster OR applications running on it.
e.g of a clustered environment -[ VCS (veritas cluster server)](https://sort.veritas.com/public/documents/sf/5.0MP3/aix/html/vcs_users/ch_about_vcs.html)

**Comment by Harkishen-Singh** [comment]
for monitoring several applications on clustered env or across multiple VM instances, we can use the IP addresses of different machines as a route and then the BR will work like said in this issue.

**Example:**

```
password: your password
test_interval:
- test: ping
  type: sec
  duration: 3
- test: jitter
  type: sec
  duration: 3
- test: req-res-delay-and-monitoring
  type: sec
  duration: 15
routes:
- method: GET
  url: https://192.203.123.55:9999
  route: about
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: q
    value: bench-routes
- method: GET
  url: http://255.306.55.11:8080
  route: best_countries/next
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: q
    value: bench-routes
utils:
  response-length:
    mode: 0
    mean: 0
  services-state:
    ping: passive
    flood-ping: passive
    jitter: passive
    req-res-delay-or-monitoring: passive


```
